language: php
php:
  - 7.0

install:
  - composer install


script:
    - ./vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 34cc056a-f93b-49f8-9017-18b226d5ede2
