language: php
php:
  - 7.0

install:
  - pip install tox
  - pip install tox codecov



before_script:
    - travis_retry composer self-update
    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - vendor/bin/phpunit --coverage-clover coverage.xml
    - tox



after_success:

     - codecov
